### ISSUE TITLE
Bug: Can't swip before I resize the browser window

### ISSUE THREAD

**Issue by wallfacer005-vip** [ksachdeva/angular-swiper#45]
The slide can't swip before I resize the browser window.
Once I resize the brwser window, then it can work very well.
Why?

**Comment by wallfacer005-vip** [comment]
I have fixed it by ng-if. 

`<ks-swiper-container  show-nav-buttons="true" ng-if="items">`

**Comment by Rex90** [comment]
Is this because you used ng-repeat on items?

**Comment by normtronics** [comment]
Im using ng-repeat and running into this issue. How can I fix it?

**Comment by brh55** [comment]
#41 <- reference for help.

**Explanation:**
This is because the swiper is started before all the slides are created through the angular ng-repeat directive. Thus a `.update` is needed to recalculate these properties, and wrapping a $timeout will force this method to be invoked at the end of the digest cycle 👍 .
